### ISSUE TITLE
FileNotFound Error (checked file, file was there)

### ISSUE THREAD

**Issue by vTalha** [Pode9935/Growtopia-Captcha-Solver#2]
![image](https://user-images.githubusercontent.com/96679958/235287975-f12bd296-29b3-4ebd-a6c4-a112625e9db3.png)

![image](https://user-images.githubusercontent.com/96679958/235287983-debf74c2-287f-44f5-8d2b-aea0f4aa79c7.png)

**Comment by Pode9935** [comment]
Try re-download, I updated the code
